#include "engine/filesystem/addonlist_state.h"

#include <iostream>
#include <string_view>
#include <vector>

namespace {

int failures = 0;

void Check(bool condition, const char* name)
{
	if (condition)
		return;
	std::cerr << "FAILED: " << name << '\n';
	++failures;
}

void TestEnabledState()
{
	constexpr std::string_view contents =
		"// generated by the addon menu\n"
		"\"AddonList\"\n"
		"{\n"
		"\t\"Enabled.Mod\" \"1\"\n"
		"\t\"Disabled.Mod\" \"0\"\n"
		"\t\"Negative.Enabled\" \"-1\"\n"
		"}\n";
	std::vector<AddonListState::Entry> entries;
	Check(AddonListState::Parse(contents, entries), "parse a complete addonlist");
	Check(entries.size() == 3, "preserve addonlist entry count");
	Check(AddonListState::IsEnabled(entries, "enabled.mod"), "match enabled addon case-insensitively");
	Check(!AddonListState::IsEnabled(entries, "DISABLED.MOD"), "exclude disabled addon case-insensitively");
	Check(AddonListState::IsEnabled(entries, "Negative.Enabled"), "match KeyValues nonzero enable semantics");
	Check(!AddonListState::IsEnabled(entries, "Missing.Mod"), "exclude addons absent from addonlist");
}

void TestDuplicateAndAtomicParsing()
{
	std::vector<AddonListState::Entry> entries;
	Check(AddonListState::Parse(
		"AddonList { Duplicate 1 duplicate 0 }", entries),
		"parse duplicate addon state");
	Check(entries.size() == 1 && !entries[0].enabled, "last duplicate addon state wins");

	const std::vector<AddonListState::Entry> original = entries;
	Check(!AddonListState::Parse("AddonList { Broken }", entries), "reject missing addon state");
	Check(entries.size() == original.size()
		&& entries[0].name == original[0].name
		&& entries[0].enabled == original[0].enabled,
		"leave prior state unchanged after parse failure");
}

void TestMalformedInput()
{
	std::vector<AddonListState::Entry> entries;
	Check(!AddonListState::Parse("", entries), "reject empty addonlist");
	Check(!AddonListState::Parse("WrongRoot { Mod 1 }", entries), "reject wrong root");
	Check(!AddonListState::Parse("AddonList { Mod yes }", entries), "reject nonnumeric state");
	Check(!AddonListState::Parse("AddonList { Mod { 1 } }", entries), "reject nested data");
	Check(!AddonListState::Parse("AddonList { Mod 1 } trailing", entries), "reject trailing data");
	Check(!AddonListState::Parse("AddonList { \"Mod 1 }", entries), "reject unterminated quoted name");
	Check(!AddonListState::Parse("AddonList { \"EnabledAddon. \" 1 }", entries), "reject Win32-aliased addon name");
	Check(!AddonListState::Parse(
		"AddonList { DisabledAddon 0 \"Disabled\\Addon\" 1 }", entries),
		"reject quoted backslash alias instead of re-enabling addon");
}

void TestSafeDirectoryNames()
{
	Check(AddonListState::IsSafeDirectoryName("Aphelions.Frontier_Overhaul"), "accept normal addon directory");
	Check(!AddonListState::IsSafeDirectoryName(""), "reject empty addon directory");
	Check(!AddonListState::IsSafeDirectoryName(".."), "reject parent addon directory");
	Check(!AddonListState::IsSafeDirectoryName("folder/child"), "reject slash in addon directory");
	Check(!AddonListState::IsSafeDirectoryName("folder\\child"), "reject backslash in addon directory");
	Check(!AddonListState::IsSafeDirectoryName("C:folder"), "reject drive syntax in addon directory");
	Check(!AddonListState::IsSafeDirectoryName("EnabledAddon. "), "reject trailing dot and space in addon directory");
	Check(!AddonListState::IsSafeDirectoryName("NUL.txt"), "reject reserved Win32 device name");
	Check(!AddonListState::IsSafeDirectoryName("lpt1.config"), "reject reserved Win32 port name");
	Check(AddonListState::IsSafeDirectoryName("com10.config"), "accept non-reserved Win32 component");
	std::string embeddedNul = "Enabled";
	embeddedNul.push_back('\0');
	embeddedNul += "Addon";
	Check(!AddonListState::IsSafeDirectoryName(embeddedNul), "reject embedded NUL in addon directory");
}

void TestRescanTransactions()
{
	using AddonListState::SearchPathUpdateEnd;
	AddonListState::RescanState state;
	const uint64_t initial = state.Generation();
	Check(state.CanPublish(initial), "allow initial generation publication");

	state.BeginSearchPathUpdate();
	const uint64_t firstUpdate = state.Generation();
	Check(state.IsSuspended(), "suspend scans during search-path update");
	Check(!state.CanPublish(initial), "reject scans from before search-path update");
	Check(!state.CanPublish(firstUpdate), "reject publication while search paths mutate");

	state.BeginSearchPathUpdate();
	const uint64_t nestedUpdate = state.Generation();
	Check(state.EndSearchPathUpdate() == SearchPathUpdateEnd::Nested,
		"identify nested search-path completion");
	Check(state.IsSuspended(), "keep scans suspended until outer update completes");
	Check(!state.CanPublish(nestedUpdate), "reject nested update generation before outer completion");

	Check(state.EndSearchPathUpdate() == SearchPathUpdateEnd::Outermost,
		"identify outer search-path completion");
	const uint64_t completed = state.Generation();
	Check(!state.IsSuspended(), "resume scans after outer search-path update");
	Check(state.CanPublish(completed), "publish only the final search-path generation");
	Check(!state.CanPublish(firstUpdate), "keep transaction generations stale after completion");

	Check(state.EndSearchPathUpdate() == SearchPathUpdateEnd::Unmatched,
		"reject unmatched search-path completion");
	Check(state.Generation() == completed, "unmatched completion does not advance generation");
	state.RequestRescan();
	Check(!state.CanPublish(completed), "manual rescan invalidates prior generation");
}

}

int main()
{
	TestEnabledState();
	TestDuplicateAndAtomicParsing();
	TestMalformedInput();
	TestSafeDirectoryNames();
	TestRescanTransactions();

	if (failures) {
		std::cerr << failures << " addonlist-state test(s) failed\n";
		return 1;
	}
	std::cout << "All addonlist-state tests passed\n";
	return 0;
}
